# Generated by Django 6.0.3 on 2026-04-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icone',
            field=models.CharField(help_text='Classe Font Awesome ex: fa-spa, fa-star, fa-heart', max_length=100),
        ),
    ]
